### 로그인 (먼저 이것을 실행하세요!)
# @name login
POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
    "email": "manager@test.com",
    "password": "testM"
}

> {%
    client.global.set("token", response.body.data.accessToken);
%}

###

### 내 정보 조회
GET http://localhost:4000/api/v1/auth/me
Authorization: Bearer {{token}}

###

### 구매 관리자 조회 - 기본 (첫 페이지, 10개 항목, 최신순)
GET http://localhost:4000/api/v1/purchase/admin/getAllPurchases
Authorization: Bearer {{token}}

###

### 구매 관리자 조회 - 페이지네이션 (2페이지, 페이지당 5개)
GET http://localhost:4000/api/v1/purchase/admin/getAllPurchases?page=2&limit=5
Authorization: Bearer {{token}}

###

### 구매 관리자 조회 - 가격 오름차순 정렬
GET http://localhost:4000/api/v1/purchase/admin/getAllPurchases?sortBy=totalPrice&order=asc
Authorization: Bearer {{token}}

###

### 구매 관리자 조회 - 가격 내림차순 정렬 + 페이지네이션
GET http://localhost:4000/api/v1/purchase/admin/getAllPurchases?page=1&limit=3&sortBy=totalPrice&order=desc
Authorization: Bearer {{token}}

###

### 구매 관리자 조회 - 요청일 오름차순 정렬
GET http://localhost:4000/api/v1/purchase/admin/getAllPurchases?sortBy=createdAt&order=asc
Authorization: Bearer {{token}}
