### 로그인 (먼저 이것을 실행하세요!)
# @name login
POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
    "email": "manager@test.com",
    "password": "testM1234!"
}

> {%
    client.global.set("token", response.body.data.accessToken);
%}

###


###
# @name getPurchaseRequestDetail - 구매 요청 상세 조회
# 구매 요청 ID를 실제 UUID로 교체해야 합니다
GET http://localhost:4000/api/v1/purchase/admin/getPurchaseRequestDetail/019b97d0-f954-7b91-af1d-77fe04495a95
Authorization: Bearer {{token}}

###
