export const ErrorCodes = {
  // 인증 관련 (AUTH_xxx)
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // 사용자 관련 (USER_xxx)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_DETAIL_CONFLICT: 'USER_DETAIL_CONFLICT',
  USER_INVALID_PASSWORD: 'USER_INVALID_PASSWORD',
  USER_ACCOUNT_LOCKED: 'USER_ACCOUNT_LOCKED',

  // 게시글 관련 (POST_xxx)
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_UNAUTHORIZED: 'POST_UNAUTHORIZED',

  // 데이터베이스 관련 (DB_xxx)
  DB_CONNECTION_FAILED: 'DB_CONNECTION_FAILED',
  DB_QUERY_FAILED: 'DB_QUERY_FAILED',
  DB_TRANSACTION_FAILED: 'DB_TRANSACTION_FAILED',
  DB_UNIQUE_CONSTRAINT_VIOLATION: 'DB_UNIQUE_CONSTRAINT_VIOLATION',

  // 검증 관련 (VAL_xxx)
  VAL_VALIDATION_ERROR: 'VAL_VALIDATION_ERROR',
  VAL_INVALID_FORMAT: 'VAL_INVALID_FORMAT',
  VAL_MISSING_FIELD: 'VAL_MISSING_FIELD',

  // 일반 (GENERAL_xxx)
  GENERAL_BAD_REQUEST: 'GENERAL_BAD_REQUEST',
  GENERAL_NOT_FOUND: 'GENERAL_NOT_FOUND',
  GENERAL_INTERNAL_ERROR: 'GENERAL_INTERNAL_ERROR',
} as const;
